version: '2'
services:
    web:
        build: .
        command: gunicorn -c gunicorn_conf.py "flask_app:create_app()"
        container_name: britecore_project
        volumes:
            - .:/code
        ports:
            - "32770:8080"
