web:
    build: .
    command: 'bash -c ''gunicorn -c gunicorn_conf.py "flask_app:create_app()"'''
    working_dir: /app/user
    environment:
        PORT: 8080
    ports:
        - '8080:8080'
shell:
    build: .
    command: bash
    working_dir: /app/user
    environment:
        PORT: 8080
    ports:
        - '8080:8080'
    volumes:
        - '.:/app/user'
