version: '2'
services:
    web:
        build: .
        #command: gunicorn -c gunicorn_conf.py flask_app:app
        command: python /code/start_server.py
        container_name: brightcove_example
        volumes:
            - .:/code
        ports:
            - "32770:8080"
